lib/utils.sh
handle the case where the file in does_pattern_exist_in_file() is not present at all
=> handle ENOENT properly in does_pattern_exist_in_file()

bin/hardening/5.2.10_disable_root_login.sh, bin/hardening/5.2.11_disable_sshd_permitemptypasswords.sh, bin/hardening/5.2.12_disable_sshd_setenv.sh, bin/hardening/5.2.13_sshd_ciphers.sh, bin/hardening/5.2.14_ssh_cry_mac.sh, bin/hardening/5.2.15_ssh_cry_kex.sh, bin/hardening/5.2.16_sshd_idle_timeout.sh, bin/hardening/5.2.17_sshd_login_grace_time.sh, bin/hardening/5.2.18_sshd_limit_access.sh, bin/hardening/5.2.19_ssh_banner.sh, bin/hardening/5.2.20_enable_ssh_pam.sh, bin/hardening/5.2.21_disable_ssh_allow_tcp_forwarding.sh, bin/hardening/5.2.22_configure_ssh_max_startups.sh, bin/hardening/5.2.23_limit_ssh_max_sessions.sh, bin/hardening/5.2.4_sshd_protocol.sh, bin/hardening/5.2.5_sshd_loglevel.sh, bin/hardening/5.2.6_disable_x11_forwarding.sh, bin/hardening/5.2.7_sshd_maxauthtries.sh, bin/hardening/5.2.8_enable_sshd_ignorerhosts.sh, bin/hardening/5.2.9_disable_sshd_hostbasedauthentication.sh, bin/hardening/99.5.2.1_ssh_auth_pubk_only.sh, bin/hardening/99.5.2.2_ssh_cry_rekey.sh, bin/hardening/99.5.2.3_ssh_disable_features.sh, bin/hardening/99.5.2.5_ssh_strict_modes.sh, bin/hardening/99.5.2.6_ssh_sys_accept_env.sh, bin/hardening/99.5.2.8_ssh_sys_sandbox.sh
Regarding @thibaultserti comment, relevant fix
=> Fix ovh/debian-cis:#25

lib/utils.sh
test if `/etc/fstab` not exists or is empty :
* if so, use mountpoint to check if it's a partition
* else use fstab
for mount option, check current mounted option if fstab doesn't exist or is empty
fix #27
=> IMP: improve partition detection in container

bin/hardening/5.2.14_ssh_cry_mac.sh, bin/hardening/5.2.15_ssh_cry_kex.sh, tests/hardening/5.2.14_ssh_cry_mac.sh
=> Update mac and kex to match debian10 CIS

bin/hardening/5.1.8_cron_users.sh
=> IMP(5.1.8): allow more restrictive permissions

bin/hardening/3.1.1_disable_ipv6.sh, bin/hardening/3.3.1_disable_source_routed_packets.sh, bin/hardening/3.3.9_disable_ipv6_router_advertisement.sh, lib/utils.sh
Modify some checks to make it pass when ipv6 is diabled
fix #50
modified:   bin/hardening/3.1.1_disable_ipv6.sh
modified:   bin/hardening/3.3.1_disable_source_routed_packets.sh
modified:   bin/hardening/3.3.9_disable_ipv6_router_advertisement.sh
modified:   lib/utils.sh
=> Add is_ipv6_disabled

bin/hardening/5.1.8_cron_users.sh
PR to add more comprehensive error/fix in bin/hardening/5.1.8_cron_users.sh
=> log details to be more comprehensive

tests/hardening/99.5.4.5.2_acc_shadow_sha512.sh
=> FIX(5.4.5.2): explicit sha512

lib/common.sh
=> Fix div function to manage 0 on numerator

bin/hardening/4.1.1.3_audit_bootloader.sh, bin/hardening/4.1.1.4_audit_backlog_limit.sh
=> FIX(4.1.1.4): bad pattern

bin/hardening/5.2.10_disable_root_login.sh, bin/hardening/5.2.11_disable_sshd_permitemptypasswords.sh, bin/hardening/5.2.12_disable_sshd_setenv.sh, bin/hardening/5.2.13_sshd_ciphers.sh, bin/hardening/5.2.16_sshd_idle_timeout.sh, bin/hardening/5.2.17_sshd_login_grace_time.sh, bin/hardening/5.2.18_sshd_limit_access.sh, bin/hardening/5.2.20_enable_ssh_pam.sh, bin/hardening/5.2.21_disable_ssh_allow_tcp_forwarding.sh, bin/hardening/5.2.22_configure_ssh_max_startups.sh, bin/hardening/5.2.23_limit_ssh_max_sessions.sh, bin/hardening/5.2.4_sshd_protocol.sh, bin/hardening/5.2.5_sshd_loglevel.sh, bin/hardening/5.2.6_disable_x11_forwarding.sh, bin/hardening/5.2.7_sshd_maxauthtries.sh, bin/hardening/5.2.8_enable_sshd_ignorerhosts.sh, bin/hardening/5.2.9_disable_sshd_hostbasedauthentication.sh, debian/changelog
=> Ignore case for sshd conf

bin/hardening/1.1.21_sticky_bit_world_writable_folder.sh, bin/hardening/6.1.10_find_world_writable_file.sh
=> Dir exceptions

cisharden.sudoers
=> FIX: add commands to sudoers

bin/hardening/2.2.1.2_configure_systemd-timesyncd.sh
=> FIX(2.2.1.2): custom func not working for systemd

bin/hardening/5.4.5_default_timeout.sh
=> Fix 5.4.5 pattern search

bin/hardening/99.5.4.5.1_acc_logindefs_sha512.sh, bin/hardening/99.5.4.5.2_acc_shadow_sha512.sh, tests/hardening/99.5.4.5.2_acc_shadow_sha512.sh
=> 99.5.4.5.2: fix bug where sha512 option rounds provoke KO

debian/changelog
=> Update changelog for release 3.2-2

debian/changelog
=> Update changelog for release 3.3-1

debian/changelog
=> bump to 3.5-1

debian/changelog
=> bump to 3.6-1

.github/workflows/pre-release.yml, .github/workflows/tagged-release.yml, debian/rules
Precedent fix was not tested thoroughly
=> fix: correct debian package compression override

bin/hardening/2.2.15_mta_localhost.sh
warn messages had typo netsat as it should be netstat
=> Update warn messages on 2.2.15_mta_localhost.sh

bin/hardening/5.2.15_ssh_cry_kex.sh
=> fix: correct debian version check on 5.2.15 configuration generation

bin/hardening/3.5.1.1_enable_firewall.sh, bin/hardening/3.5.4.1.1_net_fw_default_policy_drop.sh, tests/hardening/3.5.1.1_enable_firewall.sh, tests/hardening/3.5.4.1.1_net_fw_default_policy_drop.sh
=> feat: add nftables to firewall software allow list

README.md
@ThibaultDewailly sorry, it seems I forgot to update the README according the the PR I offered.
Cheers! :)
=> Update the documentation and add a debian/changelog entry

README.md
=> fix: typo in README. Update example of --audit usage

README.md
=> fix: update Readme to clarify project usage

bin/hardening.sh
Was broken since 2020, fixes #230
=> fix: allow set-hardening-level option usage

bin/hardening/record_mac_edit.sh, debian/control, tests/hardening/record_mac_edit.sh
Update record_mac_edit.sh to be compliant with debian11 and debian12 CIS recommendations.
fix issue #195
=> fix: update record_mac_edit.sh to use apparmor instead of selinux

lib/utils.sh
Use a more simple and generic way to ensure systemctl is present
=> fix: issue #283

bin/hardening.sh
=> fix: --set-hardening-level is messing with configuration files

README.md
=> fix: quickstart README

.pre-commit-config.yaml, bin/hardening/aide_is_installed.sh, bin/hardening/at_is_restricted.sh, bin/hardening/bluetooth_is_disabled.sh, bin/hardening/sudo_no_nopasswd.sh, bin/hardening/wireless_interfaces_disabled.sh, hooks/check_is_executable.sh, tests/hardening/aide_is_installed.sh, tests/hardening/at_is_restricted.sh, tests/hardening/bluetooth_is_disabled.sh, tests/hardening/sudo_no_nopasswd.sh, tests/hardening/wireless_interfaces_disabled.sh
- at_is_restricted.sh			-> 2.4.2.1
- wireless_interfaces_disabled.sh	-> 3.1.2
- bluetooth_is_disabled.sh 		-> 3.1.3
- sudo_no_nopasswd.sh 			-> 5.2.4
- aide_is_installed.sh 			-> 6.1.1
=> feat: add debian12 scripts
