ovh/debian-cis

lib/common.sh

with actual script if we execute :
`bin/hardening.sh --audit 2>/dev/null | grep KO`
this doesn't work and all tests appear " failed "
the file lib/main.sh contain a test that hide echo if it's not a terminal
I think the user should choose if we want process it (with pipe or IO redirection) and how
so you should remove this test.

Script output should be usefull with pipe or redirection

---

bin/hardening/10.1.3_set_password_exp_warning_days.sh

Problem: 10.1.2 and 10.1.3 scripts are identical (except for the description).
The "option" verified in 10.1.3 is the same as in 10.1.2 : PASS_MIN_DAYS. It should be PASS_WARN_AGE.

[10.1.3] set the good value for $OPTIONS

---

lib/common.sh

This way, output is more readable (especially with e.g. --audit-all)

set a fixed-size prefix for logger

---

bin/hardening.sh
debian/control
lib/common.sh
tests/docker/Dockerfile.debian10
tests/docker/Dockerfile.debian8
tests/docker/Dockerfile.debian9

In minimal environment (debian or alpine container by example) bc isn't packaged by default, 
if the script can work without hard dependance, this should be more portable
Specific feature : catch division by 0 and write N.A

Proposal to remove bc deps

---

lib/utils.sh

in minimal environment test case an error "unbound variable" appear in function "is_kernel_option_enabled",
in fact this function expect `/proc/config.gz` or `/boot/config-$(uname -r)` but not always available
in my PR, error "unbound variable" message are backed by a default value

default variable to avoid unbound variable

---

lib/utils.sh

Following previous PR, a renaming wasn't correctly done, this PR fix that (fix #46)

variable not renamed (lib/utils.sh)

---

bin/hardening/5.3.2_enable_lockout_failed_password.sh
tests/hardening/5.3.2_enable_lockout_failed_password.sh

Fix #55
See https://github.com/linux-pam/linux-pam/releases/tag/v1.4.0
pam_tally is deprecated and replaced by pam_faillock

Use pam_faillock instead of pam_tally for bullseye

---

bin/hardening/1.1.15_run_shm_nodev.sh
bin/hardening/1.1.16_run_shm_nosuid.sh
bin/hardening/1.1.17_run_shm_noexec.sh
bin/hardening/1.5.1_bootloader_ownership.sh
bin/hardening/1.5.2_bootloader_password.sh
bin/hardening/1.5.3_root_password.sh
bin/hardening/1.6.1_enable_nx_support.sh
bin/hardening/1.7.1.2_enable_apparmor.sh
bin/hardening/1.7.1.3_enforce_or_complain_apparmor.sh
bin/hardening/1.7.1.4_enforcing_apparmor.sh
bin/hardening/2.2.15_mta_localhost.sh
bin/hardening/4.1.11_record_privileged_commands.sh
bin/hardening/4.2.1.2_enable_syslog-ng.sh
bin/hardening/4.2.1.4_syslog_ng_logfiles_perm.sh
bin/hardening/4.2.1.5_syslog-ng_remote_host.sh
bin/hardening/4.2.1.6_remote_syslog-ng_acl.sh
bin/hardening/5.1.2_crontab_perm_ownership.sh
bin/hardening/5.1.3_cron_hourly_perm_ownership.sh
bin/hardening/5.1.4_cron_daily_perm_ownership.sh
bin/hardening/5.1.5_cron_weekly_perm_ownership.sh
bin/hardening/5.1.6_cron_monthly_perm_ownership.sh
bin/hardening/5.2.1_sshd_conf_perm_ownership.sh
bin/hardening/99.3.3.4_hosts_allow_permissions.sh
bin/hardening/99.3.3.5_hosts_deny_permissions.sh

* Fix #63
* Use `/dev/shm` instead of `/run/shm` if `/run/shm` doesn't exist
* Fix #65 : Replace 128 code (not managed by `hardening.sh`) by a 2 status code (check is skipped)

Check that package are installed before launching check

---

bin/hardening.sh
lib/main.sh

Currently, `LOGLEVEL` config option takes precedence over `--set-log-level` parameter.
This PR fixes that behaviour by passing `LOGLEVEL` value from `hardening.sh` to each check script.
Fixes #126

Honor --set-log-level parameter

---

bin/hardening/1.5.1_bootloader_ownership.sh

CIS Benchmark §1.5.1 states:
> Setting the permissions to read and write for root only prevents non-root users from seeing the boot parameters or changing them.
Nothing in this paragraph prevents this file to be user-writable by owner `root`, only read and write permission by group and other are forbidden.
debian's `update-grub` script creates `grub.cfg` file with mode `0600` which is compliant with CIS benchmark recommandation but fails `debian-cis` check.
This PR allows `grub.cfg`  file to have `0600` permission as well as `0400` and don't consider `0600` to be faulty anymore.

Allow grub.cfg permission to be 600

---

bin/hardening/1.5.1_bootloader_ownership.sh
bin/hardening/1.5.2_bootloader_password.sh
bin/hardening/1.7.1.2_enable_apparmor.sh

Grub detection for 1.5.1 and 1.5.2 are currently based on `grub-pc` package detection.
However, currently, OVH PCI VM default debian images and OVH baremetal systems both have no `grub-pc` package despite grub is installed and in use.
current grub installed packages from a baremetal system are:
- `grub-common`
- `grub-efi-amd64`
- `grub-efi-amd64-bin`
- `grub-efi-amd64-signed`
- `grub-legacy-ec2`
- `grub2-common`
This PR check grub presence by looking at `grub-common` package instead of `grub-pc` which should improve grub detection

Fix grub detection

---

bin/hardening/3.4.2_disable_sctp.sh

3.4.2 CIS detection example is `modprobe -n -v sctp | grep -E '(sctp|install)'`
`MODPROBE_FILTER` is necessary here because `sctp` module depends on `libcrc32c` module so even if it is disabled, `modprobe -n -v sctp` returns
```
insmod /lib/modules/4.19.0-18-cloud-amd64/kernel/lib/libcrc32c.ko 
install /bin/true
```
and detection fails
This PR fixes that behaviour by adding missing `MODPROBE_FILTER` to `is_kernel_option_enabled` call.

Fix 3.4.2 audit rule

---

bin/hardening/2.2.1.3_configure_chrony.sh
bin/hardening/2.2.1.4_configure_ntp.sh

CIS benchmark states about chrony (resp. ntp) configuration:
> This recommendation only applies if chrony (resp. ntp) is in use on the system.
This PR complies to this statement but skipping config check for chrony and ntp if they are not installed on the system.
Fixes #117

Skip NTP and Chrony config check if they are not installed

---

lib/utils.sh
tests/hardening/1.1.15_run_shm_nodev.sh
tests/hardening/1.1.16_run_shm_nosuid.sh
tests/hardening/1.1.17_run_shm_noexec.sh

The test was checking if fstab is **not** empty, so we were always falling back on /proc/mounts
Before
```
hardening                 [INFO] Treating /opt/cis-hardening/bin/hardening/1.1.14_home_nodev.sh
hardening                 [DBG ] /opt/cis-hardening/bin/hardening//opt/cis-hardening/bin/hardening/1.1.14_home_nodev.sh --audit --sudo 
1.1.14_home_nodev         [DBG ] Audit argument detected, setting status to audit
1.1.14_home_nodev         [DBG ] Unknown option passed
1.1.14_home_nodev         [INFO] Working on 1.1.14_home_nodev
1.1.14_home_nodev         [INFO] [DESCRIPTION] /home partition with nodev option.
1.1.14_home_nodev         [DBG ] Audit argument detected, setting status to audit
1.1.14_home_nodev         [INFO] Checking Configuration
1.1.14_home_nodev         [INFO] …
```

Fix empty fstab test

---

bin/hardening/3.5.4.1.1_net_fw_default_policy_drop.sh

If for some reason we want to override `PACKAGE` variable, or want to use a specific iptables cmd like `iptables-nft`, this is now possible

feat: Dissociate iptables pkg name from command

---

lib/common.sh
lib/main.sh

We made the choice to exit on error (`set -e`) in hardening scripts, and those same scripts are sourcing `lib/main.sh` which calls audit/apply functions and print the check result.
So in the case of non-zero exit status in audit/apply functions, we immediately exit without printing further information, in particular when we're running batch mode.
To reproduce, we can simulate a "failure" in any hardening script, and check the output, for example : 
- Calling the hardening script directly, we don't have any feedback except the return code about a failure
```
6.1.10_find_world_writabl [INFO] Working on 6.1.10_find_world_writable_file
6.1.10_find_world_writabl [INFO] [DESCRIPTION] Ensure no world writable files exist
6.1.10_find_world_writabl [INFO] Checking Configuration …
```

fix: Catch unexpected failures

---

bin/hardening/1.1.21_sticky_bit_world_writable_folder.sh
bin/hardening/4.1.11_record_privileged_commands.sh
bin/hardening/6.1.10_find_world_writable_file.sh
bin/hardening/6.1.11_find_unowned_files.sh
bin/hardening/6.1.12_find_ungrouped_files.sh
bin/hardening/6.1.13_find_suid_files.sh
bin/hardening/6.1.14_find_sgid_files.sh

On filesystems with too many ephemeral files, some files may disappear between the time the find command builds the files list and the time it stats them. By default, find will fail when this happens. If we pass `-ignore_readdir_race` parameter, it will simply ignore those files
In our case, as we always check for files with wrong permissions, if they are removed meanwhile, it's not an issue at all.

fix: Avoid find failures on too many files

---

bin/hardening/6.1.3_etc_gshadow-_permissions.sh
bin/hardening/6.1.6_etc_passwd-_permissions.sh
bin/hardening/6.1.7_etc_shadow-_permissions.sh
bin/hardening/6.1.8_etc_group-_permissions.sh
tests/hardening/6.1.3_etc_gshadow-_permissions.sh
tests/hardening/6.1.6_etc_passwd-_permissions.sh
tests/hardening/6.1.7_etc_shadow-_permissions.sh
tests/hardening/6.1.8_etc_group-_permissions.sh

For Section 6.1.* it should be ok if the shadowtools backup files (shadow-, passwd-, ...) are missing.
I wrapped the checks in a `does_file_exist` check.

missing shadowtools backup files is ok

---

.github/workflows/tagged-release.yml

A tag is not linked to a branch, so this test was never supposed to success

CI: Fix release action

---

bin/hardening/3.5.4.1.1_net_fw_default_policy_drop.sh

When the tested server has its iptables heavily manipulated (e.g Kubernetes)
The lock aquirement can sometimes fail, hence generating false positives
The command will retry 10 times with a 1 second interval

fix: add 10s wait timeout on iptables command

---

bin/hardening/99.1.3_acc_sudoers_no_all.sh
tests/hardening/99.1.3_acc_sudoers_no_all.sh

The `99.1.3_acc_sudoers_no_all.sh` script can sometimes timeout on servers where `/etc/sudoers.d/` has thousands of files. This patch makes it run roughly 5x faster, as tested on a server with 1500 files in `sudoers.d/`.
Closes #167.
Signed-off-by: Stephane Lesimple <stephane.lesimple@corp.ovh.com>

fix: timeout of 99.1.3

---

.github/workflows/pre-release.yml
.github/workflows/tagged-release.yml

zst compression is only available on Debian 12, since the release is built on Ubuntu latest, this was breaking release. 
Fixes #175

fix: force xz compression during .deb build

---

lib/utils.sh
tests/hardening/1.1.15_run_shm_nodev.sh
tests/hardening/1.1.16_run_shm_nosuid.sh
tests/hardening/1.1.17_run_shm_noexec.sh

Fixes #155
When real entries are present in fstab, system startup or runtime mountpoints are now properly detected Add a supplementary check in case of partition not present in fstab

fix: ensure mountpoints are properly detected

---

bin/hardening.sh

--only option was affected with a grep bug since 2017. the regex was not able to parse more than the first passed argument.
fixes #224

fix: Allow --only option to be called multiple times

---

bin/hardening/99.5.2.4_ssh_keys_from.sh
tests/hardening/99.5.2.4_ssh_keys_from.sh

This PR allows excluding multiple users from the check in 99.5.2.4.
The root user already gets a special treatment by checking /root instead of /home/* which makes sense but this was never really tested since "root" was used as the exception user in the tests.
I added a test that checks that /root is actually used for checking the root users ssh auth keys and a test that checks the new feature of excluding multiple users.
Be aware that the config/env-key EXCEPTION_USER was renamed to EXCEPTION_USER**S**

Allow multiple exception users to be defined for 99.5.2.4_ssh_keys_from

---

bin/hardening/99.5.2.4_ssh_keys_from.sh
tests/hardening/99.5.2.4_ssh_keys_from.sh

To also catch in ssk keys:
- from="10.0.1.0/8"
- from="10.0.1.0/24,10.0.2.0/24"

fix: catch cidr network in ssh keys

---

bin/hardening/5.3.4_acc_pam_sha512.sh
bin/hardening/99.5.4.5.1_acc_logindefs_sha512.sh
tests/hardening/5.3.4_acc_pam_sha512.sh
tests/hardening/99.5.4.5.1_acc_logindefs_sha512.sh

On Debian Sid / alternative distributions (such as Ubuntu), these checks would fail with `sid: integer expression expected`, which is to be expected since `$DEB_MAJ_VER` is set to a string, not an integer.
This small PR fixes that in a similar fashion to other checks in the source tree.

fix: invalid behavior on sid/alternative in 5.3.4/99.5.4.5.1

---

debian/rules

Related to #259: https://github.com/ovh/debian-cis/issues/259

fix: debian package does not include "versions"
